server:
 port:9000
spring:
  application:
   name:ApiGateway
  main:
   web-application-type:reactive
eureka:
 client:
  fetchRegistry:true
  registerWithEureka:true
 serviceUrl:
    defaultZone:http://localhost:8761/eureka
